### ISSUE TITLE
create model tarball for deployment to sagemaker

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/PeTaL-labeller#11]
https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#bring-your-own-model

https://samuelabiodun.medium.com/how-to-deploy-a-pytorch-model-on-sagemaker-aa9a38a277b6

https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/pytorch_lstm_word_language_model/pytorch_rnn.ipynb

**Comment by pjuangph** [comment]
I think this was done. made something simple and it worked

**Comment by bruffridge** [comment]
@pjuangph Can you work this now that Shruti's gone?
