### ISSUE TITLE
Preprocess new abstract data

### ISSUE THREAD

**Issue by shrutix** [nasa-petal/PeTaL-labeller#16]
Create (for 600ish articles database):
- single label rows csv
- multiple iterations of abstracts containing each label individually csv
- vector multi label rows csv

**Comment by shrutix** [comment]
- [X] single label rows csv
- [X] multiple iterations of abstracts containing each label individually csv
- [ ] vector multi label rows csv

need to update w/ new data (fixing `sense send or process information`)

**Comment by shrutix** [comment]
> need to update w/ new data (fixing `sense send or process information`)
    updated

**Comment by pjuangph** [comment]
resolved in 3992cee949e74e105239e92bb9592d04d017661c
