### ISSUE TITLE
duplicate code?

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/PeTaL-labeller#31]
What's the difference between the code in `auto-labeller/scibert/sagemaker` and `aws/pytorchmodel_endpoint`? Need to document what each contains and purpose in the readme or docs site, or remove one if it's old code.

**Comment by pjuangph** [comment]
It is duplicated functionality. So pytorchmodel_endpoint runs the api on sagemaker. What you are doing is a lambda function  that uses sagemaker. There's several ways of hosting the API either within sagemaker or from lambda (that i know of). Where do you see this code?

**Comment by bruffridge** [comment]
https://github.com/nasa-petal/PeTaL-labeller/tree/main/aws/pytorchmodel_endpoint

**Comment by pjuangph** [comment]
That can be deleted. we are not using it anymore.

**Comment by bruffridge** [comment]
closed in 135fb8bd3d31eec3c7a5773b70861cc0bf3b010a
