### ISSUE TITLE
Verify input format expected by MATCH for unlabelled papers

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/PeTaL-labeller#48]
Is it the same as the format for the training data just without the `label` field? See #43 . This issue blocks #45.

**Comment by elkong** [comment]
Looks like MATCH's preprocessing scripts expect the json files to come with a 'label' field, but you can omit the labels file they produce in testing.

For consistency, my recommendation would be to include a 'label' field in the json objects, but it can be an empty array.

**Comment by bruffridge** [comment]
So to generate a prediction for an unlabelled paper, you invoke the model with json formatted as described here? https://github.com/nasa-petal/PeTaL-labeller/issues/43

**Comment by elkong** [comment]
Yes, that format should do.
