### ISSUE TITLE
Only 409 papers with labels in cleaned_lens_output.json, should be 701

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/PeTaL-labeller#50]
Maybe try looking up by doi [instead of title](https://github.com/nasa-petal/PeTaL-labeller/blob/main/scripts/lens-cleaner/lensCleaner.py#L55)? If you want to try that, you'll have to adjust the [curl command](https://github.com/nasa-petal/PeTaL-labeller/tree/main/data) to include the doi field in the json response from lens.org.

**Comment by dsmith111** [comment]
Searching using DOI _or_ title leads to 640 labeled results.
